# Test against this version of Node.js
environment:
  nodejs_version: "4.2"

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g bower
  - bower install

# "build" means "build using the project or solution file", which we don't
# have. So turn this off.
build: off
